### ISSUE TITLE
sobre a atividade

### ISSUE THREAD

**Issue by diegolpes77** [ProfRonan/matrizes-e-vetores-diegolpes77#2]
será necessário que eu refaça a de matrizes?
até onde eu vi eu passei em todos os testes de vetores

**Comment by SeuRonao** [comment]
Quando você fecha a issue eu imagino que tenha tirado a dúvida de alguma outra forma, correto?

**Comment by diegolpes77** [comment]
Nao me toquei que havia fechado a issue

Em seg, 10 de jul de 2023 20:42, Ronan Soares ***@***.***>
escreveu:

**Comment by SeuRonao** [comment]
Coloquei a resposta em #1
